#!/bin/sh
. /etc/os-release
green="[92m"
yellow="[93m"
reg="[95m"
white="[0m"
printf '%s\n' "
  ${yellow}$(whoami)@$(hostname)
  ${green}ω${white} ~ ${PRETTY_NAME}
  ${green}σ${white} ~ ${SHELL##*/}
  ${green}υ${white} ~ $(wmctrl -m | sed -n '1p' | sed 's/Name: //')
  ${green}κ${white} ~ $(uname -r)
  ${green}ι${white} ~ $(ps -ocomm --no-headers 1)
  [30m███[31m███[32m███[33m███[34m███[35m███[36m███[37m███
  [90m███[91m███[92m███[93m███[94m███[95m███[96m███[97m███
"
