#!/usr/bin/bash

servstart() {
    doas ln -s /etc/sv/"$1" /var/service/
}
servstop() {
    doas rm /var/service/"$1"
}
helpFunction() {
    printf '%s\n' "
servctl - enable and disable services
OPTIONS
    -E - enable a service
    -D - disable a service
    -H - display this help
    "
}
if [ -z "$1" ]; then
  helpFunction
fi
while getopts ":E:D:H" opt; do
   case "$opt" in
      E ) servstart ;;
      D ) servstop ;;
      H ) helpFunction ;;
   esac
done
