#!/usr/bin/ksh
helpFunction() {
    printf '%s\n' "
servctl - enable and disable services
OPTIONS
    -E - enable a service
    -D - disable a service
    -T - start a service
    -B - stop a service
    -R - restart a service
    -H - display this help
    -L - list running services (if next arg is created, lists sv services)
    "
}
if [ -z "$1" ]; then
  helpFunction
fi
while getopts "E(enable):D(disable):H(help)T(top):B(bottom):R(restart):L(list)S(status):" optchar; do
   case $optchar in
      E ) doas ln -s /etc/sv/"$OPTARG" /var/service/ ;;
      D ) doas rm /var/service/"$OPTARG" ;;
      H ) helpFunction ;;
      T ) doas sv u "$OPTARG" ;;
      B ) doas sv d "$OPTARG" ;;
      R ) doas sv r "$OPTARG" ;;
      L ) [[ $2 = "created" ]] && lsd /etc/sv || lsd /var/service ;;
      S ) doas sv s "$OPTARG" ;;
   esac
done
