#!/usr/bin/ksh
helpFunction() {
    printf '%s\n' "
servctl - enable and disable services
OPTIONS
    -E, --enable  - enable a service
    -D, --disable - disable a service
    -T, --top     - start a service
    -B, --bottom  - stop a service
    -R, --restart - restart a service
    -L, --list    - list running services (if next arg is created, lists all services)
    -S, --status  - show service status, so sweet
    -H, --help    - display this help
        --man     - display the man page (kinda)
    "
    exit 1
}
[ -z $1 ] && helpFunction
USAGE=$'[-?\n@(#)$Id: 'servctl' $\n]'
USAGE+="[-author?harlow]"
USAGE+="[-copyright?no one]"
USAGE+="[-license?none, i don't license my shit]"
USAGE+="[+NAME?servctl - sv wrapper]"
USAGE+="[+DESCRIPTION?an sv wrapper for param lovers]"
USAGE+="[E:enable?enable a service]"
USAGE+="[D:disable?disable a service]"
USAGE+="[T:top?turn a service on]"
USAGE+="[B:bottom?turn a service off]"
USAGE+="[R:restart?restart a service (useful for breakages)]"
USAGE+="[L:list?list enabled services (or all if next arg is created)]"
USAGE+="[S:status?show status of a service]"
USAGE+="[H:help?display the help]"
USAGE+="[10:edit?edit a service]"
while getopts "$USAGE" optchar; do
   case $optchar in
      E ) doas ln -s /etc/sv/"$2" /var/service/ ;;
      D ) doas rm /var/service/"$2" ;;
      H ) helpFunction ;;
      T ) doas sv u "$2" ;;
      B ) doas sv d "$2" ;;
      R ) doas sv restart "$2" ;;
      L ) [[ $2 = "created" ]] && ls /etc/sv || ls /var/service ;;
      S ) doas sv s "$2" ;;
      10 ) doas vim /etc/sv/"$2"/run
   esac
done
